name: BankPlus
version: '${version}' # Remember to change the one in BankPlus main class.
main: me.pulsi_.bankplus.BankPlus
api-version: '1.21'
authors: [ Pulsi_ ]
description: The best free bank plugin on internet!
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - Essentials
  - EconomyPlus
  - CMI
load: POSTWORLD
commands:
  bankplus:
    aliases: [bankp, bank, bp]

  banktop:
    aliases: [btop]