name: BankPlus
version: 5.7
main: me.pulsi_.bankplus.BankPlus
api-version: 1.13
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - Essentials
  - EconomyPlus
authors: [ Pulsi_ ]
load: POSTWORLD
description: The best bank plugin on Spigot!
commands:
  bankplus:
    aliases: [bankp, bank, bp]

  banktop:
    aliases: [btop]