name: BankPlus
version: '${version}' # Remember to change the one in BankPlus main class.
main: me.pulsi_.bankplus.BankPlus
api-version: '1.21'
authors: [ Pulsi_ ]
description: Bank plugin fully customizable.
