name: BankPlus
version: '6.3' # Remember to also change in BankPlus.java and build.gradle
main: me.pulsi_.bankplus.BankPlus
api-version: '1.21'
authors: [ Pulsi_ ]
description: Bank plugin fully customizable.
